version: '3.8'
services:
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    environment:
      # KAFKA_PROCESS_ROLES: "broker,controller"
      # KAFKA_NODE_ID: 1
      # KAFKA_CONTROLLER_QUORUM_VOTERS: "1@localhost:9093"
      # KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
      # KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      # KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      # KAFKA_LOG_RETENTION_HOURS: 168
      # KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      # KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      # KAFKA_MIN_INSYNC_REPLICAS: 1
      # KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_LOG4J_OPTS: "-Dlog4j.configuration=file:/opt/kafka/config/log4j.properties" # Add this line
    volumes:
      - ./kafka-data:/var/lib/kafka/data
      - ./kafka-config:/etc/kafka # Mount custom config file
      - ./log4j.properties:/opt/kafka/config/log4j.properties # Mount the log4j properties
      - ./log4j.properties:/opt/kafka/config/log4j.properties # Mount the log4j properties file to /opt/kafka/config/
    ports:
      - "9092:9092"
      - "9093:9093"
    command: ["/bin/sh", "-c", "kafka-storage format -t b3Q05DyPSk6EMX3jMXuZ5Q -c /etc/kafka/server.properties --ignore-formatted && kafka-server-start /etc/kafka/server.properties"]
